server:
  port: 7070
  
  #nohup java -jar -Dspring.profiles.active=prod auth-0.0.1-SNAPSHOT.jar > auth.log &
  
spring:
  profiles:
    active: default 
  servlet: 
    #multipart 파일처리 조건
    multipart:      max-file-size: -1      max-request-size: -1
  #database 접속 정보      datasource:
        #jdbc:mysql://엔드포인트 복붙/데이터베이스(스키마)?옵션    url: jdbc:mysql://mysql-1.co2rhj8bx4dt.ap-northeast-2.rds.amazonaws.com/auth?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true #데이터처리할 때 SQL문을 보여줌
    generate-ddl: true #클래스 정의에 따른 테이블 및 데이터베이스 객체 생성, repository와 entity가 있으면 객체 만들어짐
  redis:
    host: 127.0.0.1
    port: 6379
    
---
spring:
  profiles: prod
  redis:    host: 13.124.190.225
    port: 6379
    password: foobared
 